bStats: true
nameColors: false
unbreakables: false
flightTime: true
durability: true
illegalBlocks: true
nbtContainers: true
overstackedItems: true
allowCollectibles: true
conflictingEnchantments: true
maxEnchantments: true
shulkerBoxes: true
maxBooksInShulker: 10
maxBooksShulkersInInventory: 3
attributeModifiers: true
customPotionEffects: true
hideFlags: true
suspiciousStewEffects: true

illegalMaterials:
  - "bedrock"
  - "end_portal_frame"
  - "barrier"
  - "structure_block"
  - "structure_void"
  - "spawner"
  - "command_block"
  - "chain_command_block"
  - "command_block_minecart"
  - "repeating_command_block"
  - "*_spawn_egg"
  - "jigsaw"
  - "light"
  - "debug_stick"
  - "vault"
  - "trial_spawner"
  - "reinforced_deepslate"
  - "bundle"

# technically illegal, but not reverting these by default
# - "chorus_plant"
# - "dirt_path"
# - "farmland"
# - "budding_amethyst"
# - "infested_*"
# - "dirt_path"
# - "knowledge_book"

