bStats: true
nameColors: false
unbreakables: false
flightTime: true
durability: true
illegalBlocks: true
nbtContainers: true
blockStates:
  enabled: true
  keys:
    - "can_summon"
    - "disarmed"
    - "extended"
    - "has_record"
    - "slot_0_occupied"
    - "slot_1_occupied"
    - "slot_2_occupied"
    - "slot_3_occupied"
    - "slot_4_occupied"
    - "slot_5_occupied"
    - "waterlogged"
overstackedItems: true
allowCollectibles: true
conflictingEnchantments: true
maxEnchantments: true
shulkerBoxes: true
maxBooksInShulker: 10
maxBooksShulkersInInventory: 3
attributeModifiers: true
customPotionEffects: true
hideFlags: false
suspiciousStewEffects: true

illegalMaterials:
  - "bedrock"
  - "end_portal_frame"
  - "barrier"
  - "structure_block"
  - "structure_void"
  - "spawner"
  - "command_block"
  - "chain_command_block"
  - "command_block_minecart"
  - "repeating_command_block"
  - "*_spawn_egg"
  - "jigsaw"
  - "light"
  - "debug_stick"
  - "vault"
  - "trial_spawner"
  - "reinforced_deepslate"
  - "bundle"

# technically illegal, but not reverting these by default
# - "chorus_plant"
# - "dirt_path"
# - "farmland"
# - "budding_amethyst"
# - "infested_*"
# - "dirt_path"
# - "knowledge_book"

